name: AporiaxtenCrowns
main: me.uraniumape.crown.CrownCore
version: 1.2
author: Uranium_Ape
api-version: 1.18
commands:
  ac:
    description: "Crown help menu"
    usage: /<command>
  am:
    description: "Misc help menu"
    usage: /<command>