package me.uraniumape.crown;

public enum Item_Type {
	COPPER_HELMET,
	COPPER_CHESTPLATE,
	COPPER_LEGGINGS,
	COPPER_BOOTS,
	
	COPPER_SWORD,
	COPPER_AXE,
	COPPER_PICKAXE,
	COPPER_HOE,
	COPPER_SHOVEL,
	
	ROYAL_HELMET,
	ROYAL_CHESTPLATE,
	ROYAL_LEGGINGS,
	ROYAL_BOOTS
}
